server:
  servlet:
    context-path: /planner

spring:
  liquibase:
    change-log: classpath:/db/changelog/master.xml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/planner_for_tutor
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true



    password: guest
    port: '5672'
    host: localhost
    username: guest

planner:
  weekDaysOff: [SATURDAY, SUNDAY]
  holidayApiUrl: https://date.nager.at/api/v3/PublicHolidays/2023/PL

holidayClient:
  type: rest-template

rabbitmq:
  routing:
    key: email_routing_key
    key2: email_routing_key2
    json:
      key: email_routing_json_key
      key2: email_routing_json_key2
  queue:
    json:
      name: email_json
      name2: email_json2
  exchange:
    name: email_exchange
    name2: email_exchange2

preconfigured-users:
  enabled: true
  users:
    -
      firstName: Jan
      lastName: Kowalski
      email: jan.kowalski@mail.com
      password: password
      role: ADMIN
    -
      firstName: Adam
      lastName: Nowak
      email: adam.nowak@mail.com
      password: password
      role: USER
