spring:
  liquibase:
    change-log: classpath:/db/changelog/master.xml
    enabled: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

planner:
  weekDaysOff: [SATURDAY, SUNDAY]
  holidayApiUrl: https://date.nager.at/api/v3/PublicHolidays/2023/PL

holidayClient:
  type: rest-template