spring:
  liquibase:
    change-log: classpath:/db/changelog/master.xml
    enabled: false
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
