spring:
  liquibase:
    change-log: classpath:/db/changelog/master.xml
    enabled: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  rabbitmq:
    password: guest
    port: '5672'
    host: localhost
    username: guest

planner:
  weekDaysOff: [SATURDAY, SUNDAY]
  holidayApiUrl: https://date.nager.at/api/v3/PublicHolidays/2023/PL

holidayClient:
  type: rest-template

rabbitmq:
  routing:
    key: email_routing_key
    json:
      key: email_routing_json_key
  queue:
    json:
      name: email_json
  exchange:
    name: email_exchange
rabbit:
  queue:
    name: email
