package com.babinska.plannerfortutor.student;

public enum SchoolClass {
  ELEMENTARY_SCHOOL_4TH_GRADE,
  ELEMENTARY_SCHOOL_5TH_GRADE,
  ELEMENTARY_SCHOOL_6TH_GRADE,
  ELEMENTARY_SCHOOL_7TH_GRADE,
  ELEMENTARY_SCHOOL_8TH_GRADE,
  HIGH_SCHOOL_1TH_GRADE,
  HIGH_SCHOOL_2TH_GRADE,
  HIGH_SCHOOL_3TH_GRADE,
  HIGH_SCHOOL_4TH_GRADE,
  HIGH_SCHOOL_5TH_GRADE,
}
