package com.babinska.PlannerForTutor.student;

public enum SchoolClass {
  ELEMENTARY_SCHOOL_4TH_GRADE,
  ELEMENTARY_SCHOOL_5TH_GRADE,
  ELEMENTARY_SCHOOL_6TH_GRADE,
  ELEMENTARY_SCHOOL_7TH_GRADE,
  ELEMENTARY_SCHOOL_8TH_GRADE,
  PRIMARY_SCHOOL_1TH_GRADE,
  PRIMARY_SCHOOL_2TH_GRADE,
  PRIMARY_SCHOOL_3TH_GRADE,
  PRIMARY_SCHOOL_4TH_GRADE,
  PRIMARY_SCHOOL_5TH_GRADE,
}
